VOCAB_SIZE = 16000

EMBEDDING_DIM = 384

NUM_HEADS = 8

NUM_LAYERS = 6

MAX_SEQUENCE_LENGTH = 128

DROPOUT = 0.1

FFN_HIDDEN_DIM = 1536
from config.model_config import VOCAB_SIZE, EMBEDDING_DIM, NUM_HEADS, NUM_LAYERS, MAX_SEQUENCE_LENGTH, DROPOUT

__all__ = [
    "VOCAB_SIZE",
    "EMBEDDING_DIM",
    "NUM_HEADS",
    "NUM_LAYERS",
    "MAX_SEQUENCE_LENGTH",
    "DROPOUT",
]
