BATCH_SIZE = 16

LEARNING_RATE = 3e-4

EPOCHS = 10

DEVICE = "cuda"

CHECKPOINT_DIR = "checkpoints"

DATA_DIR = "data"

NUM_WORKERS = 2

PIN_MEMORY = True

SHUFFLE_DATASET = True

SAVE_EVERY_EPOCH = True

GRADIENT_CLIP_VALUE = 1.0

TINYSTORIES_SUBSET_SIZE = 100000

GENERATION_MAX_LENGTH = 100

TEMPERATURE = 0.8

TOP_K = 40

TRAIN_SPLIT = 0.9
from config.training_config import BATCH_SIZE, LEARNING_RATE, EPOCHS, DEVICE, CHECKPOINT_DIR

__all__ = ["BATCH_SIZE", "LEARNING_RATE", "EPOCHS", "DEVICE", "CHECKPOINT_DIR"]
